// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/fake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakeRequest) Reset() {
	*x = FakeRequest{}
	mi := &file_api_fake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeRequest) ProtoMessage() {}

func (x *FakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeRequest.ProtoReflect.Descriptor instead.
func (*FakeRequest) Descriptor() ([]byte, []int) {
	return file_api_fake_proto_rawDescGZIP(), []int{0}
}

type FakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakeResponse) Reset() {
	*x = FakeResponse{}
	mi := &file_api_fake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeResponse) ProtoMessage() {}

func (x *FakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeResponse.ProtoReflect.Descriptor instead.
func (*FakeResponse) Descriptor() ([]byte, []int) {
	return file_api_fake_proto_rawDescGZIP(), []int{1}
}

func (x *FakeResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *FakeResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *FakeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_fake_proto protoreflect.FileDescriptor

const file_api_fake_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/fake.proto\x12\afakesvc\"\r\n" +
	"\vFakeRequest\"T\n" +
	"\fFakeResponse\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg2K\n" +
	"\vFakeService\x12<\n" +
	"\tGetStream\x12\x14.fakesvc.FakeRequest\x1a\x15.fakesvc.FakeResponse\"\x000\x01B\x13Z\x11pkg/fakesvc/protob\x06proto3"

var (
	file_api_fake_proto_rawDescOnce sync.Once
	file_api_fake_proto_rawDescData []byte
)

func file_api_fake_proto_rawDescGZIP() []byte {
	file_api_fake_proto_rawDescOnce.Do(func() {
		file_api_fake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_fake_proto_rawDesc), len(file_api_fake_proto_rawDesc)))
	})
	return file_api_fake_proto_rawDescData
}

var file_api_fake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_fake_proto_goTypes = []any{
	(*FakeRequest)(nil),  // 0: fakesvc.FakeRequest
	(*FakeResponse)(nil), // 1: fakesvc.FakeResponse
}
var file_api_fake_proto_depIdxs = []int32{
	0, // 0: fakesvc.FakeService.GetStream:input_type -> fakesvc.FakeRequest
	1, // 1: fakesvc.FakeService.GetStream:output_type -> fakesvc.FakeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_fake_proto_init() }
func file_api_fake_proto_init() {
	if File_api_fake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_fake_proto_rawDesc), len(file_api_fake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_fake_proto_goTypes,
		DependencyIndexes: file_api_fake_proto_depIdxs,
		MessageInfos:      file_api_fake_proto_msgTypes,
	}.Build()
	File_api_fake_proto = out.File
	file_api_fake_proto_goTypes = nil
	file_api_fake_proto_depIdxs = nil
}
