// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/fake.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FakeService_GetStream_FullMethodName = "/fakesvc.FakeService/GetStream"
)

// FakeServiceClient is the client API for FakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FakeService 假服务
type FakeServiceClient interface {
	GetStream(ctx context.Context, in *FakeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FakeResponse], error)
}

type fakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFakeServiceClient(cc grpc.ClientConnInterface) FakeServiceClient {
	return &fakeServiceClient{cc}
}

func (c *fakeServiceClient) GetStream(ctx context.Context, in *FakeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FakeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FakeService_ServiceDesc.Streams[0], FakeService_GetStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FakeRequest, FakeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FakeService_GetStreamClient = grpc.ServerStreamingClient[FakeResponse]

// FakeServiceServer is the server API for FakeService service.
// All implementations must embed UnimplementedFakeServiceServer
// for forward compatibility.
//
// FakeService 假服务
type FakeServiceServer interface {
	GetStream(*FakeRequest, grpc.ServerStreamingServer[FakeResponse]) error
	mustEmbedUnimplementedFakeServiceServer()
}

// UnimplementedFakeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFakeServiceServer struct{}

func (UnimplementedFakeServiceServer) GetStream(*FakeRequest, grpc.ServerStreamingServer[FakeResponse]) error {
	return status.Error(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedFakeServiceServer) mustEmbedUnimplementedFakeServiceServer() {}
func (UnimplementedFakeServiceServer) testEmbeddedByValue()                     {}

// UnsafeFakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FakeServiceServer will
// result in compilation errors.
type UnsafeFakeServiceServer interface {
	mustEmbedUnimplementedFakeServiceServer()
}

func RegisterFakeServiceServer(s grpc.ServiceRegistrar, srv FakeServiceServer) {
	// If the following call panics, it indicates UnimplementedFakeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FakeService_ServiceDesc, srv)
}

func _FakeService_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FakeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FakeServiceServer).GetStream(m, &grpc.GenericServerStream[FakeRequest, FakeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FakeService_GetStreamServer = grpc.ServerStreamingServer[FakeResponse]

// FakeService_ServiceDesc is the grpc.ServiceDesc for FakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fakesvc.FakeService",
	HandlerType: (*FakeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _FakeService_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/fake.proto",
}
